### ISSUE TITLE
Why not vue?

### ISSUE THREAD

**Issue by 123ysz123** [1086-loves-programming/code-blockly#2]
# My suggestion
Use Vue Js can better deploy the project and reduce the time for development and maintenance. It is also recommended to deploy the project to the server, which is flexible and can add a back end.

**Comment by 1086-loves-programming** [comment]
We will consider your suggestions, thank you

**Comment by CoolPlayLin** [comment]
> # My suggestion
> Use Vue Js can better deploy the project and reduce the time for development and maintenance. It is also recommended to deploy the project to the server, which is flexible and can add a back end.

6

**Comment by 1086-loves-programming** [comment]
Hi, long time no see. We've got the Google Blockly's Vue sample code, which we'll try to use in our project

**Comment by 123ysz123** [comment]
> Hi, long time no see. We've got the Google Blockly's Vue sample code, which we'll try to use in our project

OK, but you'd better use vite. But you must have a server. It cannot be used in github pages.
